//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class BotTexts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BotTexts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.BotTexts", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to translate something else?.
        /// </summary>
        internal static string AfterTranslationQuestion {
            get {
                return ResourceManager.GetString("AfterTranslationQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want me to look up something for you?.
        /// </summary>
        internal static string AnotherWikiSearchQuestion {
            get {
                return ResourceManager.GetString("AnotherWikiSearchQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        internal static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I can support you for the following topics:.
        /// </summary>
        internal static string CategorySelectionQuestion {
            get {
                return ResourceManager.GetString("CategorySelectionQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I already create the link to our human support team. Please click on the link to open the email an check the text before sending it. Event I make mistakes from time to time. Here is the link:.
        /// </summary>
        internal static string ClickLinkForSupportMail {
            get {
                return ResourceManager.GetString("ClickLinkForSupportMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I am very sorry, but I could not translate the text..
        /// </summary>
        internal static string CouldNotTranslateText {
            get {
                return ResourceManager.GetString("CouldNotTranslateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I could not connect to my database. I hope this problem will be solved soon..
        /// </summary>
        internal static string DatebaseNotAvailable {
            get {
                return ResourceManager.GetString("DatebaseNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want me to remember that question and prepare an email to support?.
        /// </summary>
        internal static string EscalateToSupportQuestion {
            get {
                return ResourceManager.GetString("EscalateToSupportQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How would you rate my supprt on a scale from 1 (really bad) to 9 (perfect)?.
        /// </summary>
        internal static string ExperienceRatingQuestion {
            get {
                return ResourceManager.GetString("ExperienceRatingQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I need your feedback to improve..
        /// </summary>
        internal static string FeedbackIntro {
            get {
                return ResourceManager.GetString("FeedbackIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks for you feedback..
        /// </summary>
        internal static string FeedbackNotSaved {
            get {
                return ResourceManager.GetString("FeedbackNotSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please use a number from 1 (really bad) to 9 (perfect) for your feedback. Thank you!.
        /// </summary>
        internal static string FeedbackNoWrongNumber {
            get {
                return ResourceManager.GetString("FeedbackNoWrongNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I there further feedback you would like to provide?.
        /// </summary>
        internal static string FeedbackQuestion {
            get {
                return ResourceManager.GetString("FeedbackQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I saved you feedback. Thank you..
        /// </summary>
        internal static string FeedbackSaved {
            get {
                return ResourceManager.GetString("FeedbackSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I fould more answer that might help. This is what I found:.
        /// </summary>
        internal static string FoundMoreAnswers {
            get {
                return ResourceManager.GetString("FoundMoreAnswers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I found the following answer in my database:.
        /// </summary>
        internal static string FoundQnAAnswer {
            get {
                return ResourceManager.GetString("FoundQnAAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to French.
        /// </summary>
        internal static string French {
            get {
                return ResourceManager.GetString("French", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to help me by providing feedback?.
        /// </summary>
        internal static string GiveFeedbackQuesiton {
            get {
                return ResourceManager.GetString("GiveFeedbackQuesiton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Great. Always happy to help..
        /// </summary>
        internal static string GladToHelp {
            get {
                return ResourceManager.GetString("GladToHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello {0}!.
        /// </summary>
        internal static string GreetingGeneral {
            get {
                return ResourceManager.GetString("GreetingGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can ask for help anytime, by typing &apos;help&apos;..
        /// </summary>
        internal static string HelpHint {
            get {
                return ResourceManager.GetString("HelpHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Italian.
        /// </summary>
        internal static string Italian {
            get {
                return ResourceManager.GetString("Italian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something else.
        /// </summary>
        internal static string Misc {
            get {
                return ResourceManager.GetString("Misc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Need assisstance?.
        /// </summary>
        internal static string NeedHelpQuestion {
            get {
                return ResourceManager.GetString("NeedHelpQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok, I did not expect that. I prefer not to answer to that one..
        /// </summary>
        internal static string NoAnswerSmallTalk {
            get {
                return ResourceManager.GetString("NoAnswerSmallTalk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No problem. Maybe next time..
        /// </summary>
        internal static string NoFeedbackReply {
            get {
                return ResourceManager.GetString("NoFeedbackReply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I don&apos;t have an answer for that, but I have amazing human colleagues who are always happy to help..
        /// </summary>
        internal static string NoQnAReply {
            get {
                return ResourceManager.GetString("NoQnAReply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I could not find any information on that. Maybe Open Thesaurus doesn&apos;t answer right now or you are looking for something really special..
        /// </summary>
        internal static string NoThesaurusReply {
            get {
                return ResourceManager.GetString("NoThesaurusReply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I could not find any information on that. Maybe Wikipedia doesn&apos;t answer right now or you are looking for something really special..
        /// </summary>
        internal static string NoWikiReply {
            get {
                return ResourceManager.GetString("NoWikiReply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email to support.
        /// </summary>
        internal static string OpenSupportMailText {
            get {
                return ResourceManager.GetString("OpenSupportMailText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please use the buttons for your reply..
        /// </summary>
        internal static string PleaseUseButtons {
            get {
                return ResourceManager.GetString("PleaseUseButtons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Does this answer your question?.
        /// </summary>
        internal static string ProblemSolvedQuestion {
            get {
                return ResourceManager.GetString("ProblemSolvedQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How can I help you with {0}?.
        /// </summary>
        internal static string QnAQuestion {
            get {
                return ResourceManager.GetString("QnAQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, but I couldn&apos;t save you question..
        /// </summary>
        internal static string QuestionNotSaved {
            get {
                return ResourceManager.GetString("QuestionNotSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I will remember your question and will try to add an answer to my knowledge base as soon as possible. Sorry about the inconvenience..
        /// </summary>
        internal static string QuestionSaved {
            get {
                return ResourceManager.GetString("QuestionSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How can I help next?.
        /// </summary>
        internal static string RootDialogCompleted {
            get {
                return ResourceManager.GetString("RootDialogCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I am looking for an answer. Give me a few seconds to think..
        /// </summary>
        internal static string SearchingDatabases {
            get {
                return ResourceManager.GetString("SearchingDatabases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Look up synonym.
        /// </summary>
        internal static string SearchThesaurusTerm {
            get {
                return ResourceManager.GetString("SearchThesaurusTerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use encyclopedia.
        /// </summary>
        internal static string SearchWikipediaTerm {
            get {
                return ResourceManager.GetString("SearchWikipediaTerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spansih.
        /// </summary>
        internal static string Spanish {
            get {
                return ResourceManager.GetString("Spanish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This%20is%20an%20auto%20generated%20eMail%20from%20SupportBot.%0D%0A%0D%0A{0}Question:%20{1}%0D%0A%0D%0AWith%20best%20regards%20.
        /// </summary>
        internal static string SupportMailBody {
            get {
                return ResourceManager.GetString("SupportMailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support Request {0}.
        /// </summary>
        internal static string SupportMailSubject {
            get {
                return ResourceManager.GetString("SupportMailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One of my services doesn&apos;t talk to me right now or there has been some other problem. I hope I can solve that problem soon..
        /// </summary>
        internal static string TechnicalProblemWithService {
            get {
                return ResourceManager.GetString("TechnicalProblemWithService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IT Question.
        /// </summary>
        internal static string TechnicalQuestion {
            get {
                return ResourceManager.GetString("TechnicalQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For which topic do you need help?.
        /// </summary>
        internal static string TechnicalTopicQuestion {
            get {
                return ResourceManager.GetString("TechnicalTopicQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here is the translation:.
        /// </summary>
        internal static string TextFromTranslation {
            get {
                return ResourceManager.GetString("TextFromTranslation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For which term do you want to find a synonym?.
        /// </summary>
        internal static string ThesaurusSearchQuestion {
            get {
                return ResourceManager.GetString("ThesaurusSearchQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translate into a different language.
        /// </summary>
        internal static string TranslateInDifferentLanguageOption {
            get {
                return ResourceManager.GetString("TranslateInDifferentLanguageOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translate into the same language.
        /// </summary>
        internal static string TranslateSameLanguageOption {
            get {
                return ResourceManager.GetString("TranslateSameLanguageOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translate text.
        /// </summary>
        internal static string TranslateTerm {
            get {
                return ResourceManager.GetString("TranslateTerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Which language do you want to translate to?.
        /// </summary>
        internal static string TranslationLanguageQuestion {
            get {
                return ResourceManager.GetString("TranslationLanguageQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello, I am your SupportBot. I can answer IT question, look up things and translate text. I can even answer some fun question..
        /// </summary>
        internal static string WelcomeText {
            get {
                return ResourceManager.GetString("WelcomeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello, I am SupportBot and can help you with the following topics:.
        /// </summary>
        internal static string WelcomeTextCategories {
            get {
                return ResourceManager.GetString("WelcomeTextCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What do you want me to translate into {0}?.
        /// </summary>
        internal static string WhatToTranslateQuestion {
            get {
                return ResourceManager.GetString("WhatToTranslateQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Which term do you want to look up in the encyclopedia?.
        /// </summary>
        internal static string WikiSearchQuestion {
            get {
                return ResourceManager.GetString("WikiSearchQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
